
let frase = 'ABLE, ACEITA, ACEITAÇÃO, ACEITÁVEL, ACEITO, ACEITANDO, AÇÃO, ATIVAR, ADD, ADIÇÃO, ADORÁVEL, VANTAGEM, AFIRME, SEM IDADE, CONCORDA, AGRADÁVEL, ABUNDÂNCIA, PRESTAÇÃO DE CONTAS, REALIZAÇÃO, REALIZAR, EXATIDÃO, FAÇANHA, ALCANÇAR, AGRADECIMENTO, ADAPTABILIDADE, AGILIDADE, AGILIDADE, AMBIÇÃO, ANTECIPAÇÃO, AGRADECEMOS, GRATA, ASSERTIVIDADE, ASSERTIVA, ATENÇÃO, AUDÁCIA, CONSCIÊNCIA, AUTÊNTICO, AUTENTICIDADE, ABRACADABRA, ATRAÇÃO, PERMITEM, PERMITINDO, CARINHO, CARINHOSO, ABSORVIDO, SURPREENDIDO, ANIMATE, ANIMADO, ANIMANDO, ANIMAÇÃO, ARDENTE, SURPRESA, IMPRESSIONANTE, EXCITADO, SURPREENDIDO, ASTONISHING, DIVERTIDO, ALOHA, ADORE, ADMIRE, ADMIRÁVEL, ANGEL, ANGÉLICO, O ALTRUÍSMO, ALTRUÍSTAS, ABUNDAM, ABUNDANTE, ABUNDANTE, ABSOLUTO, ABSOLUTAMENTE, ACESSÍVEL, ACLAMADO, ACOMODAR, ACOMODADO, ACOMODAÇÃO, ACOMODANDO, AMPLA, APRECIATIVO ALEGRIA, AFÁVEL, VIVACIDADE, AMÁVEL, SURPRESA, ATRATIVO, ALIVE, VIVACIDADE, ACCLAIM, SATISFAÇÃO ABUNDANTE, ACLAMAÇÃO, REALIZADO, REALIZAÇÕES, PRECISO, PRECISAMENTE, ACHIEVABLE, REALIZAÇÕES, AÇÃO PARA FELICIDADE, CONSTRUTIVA, ATOS DE BONDADE, ADAPTÁVEL, ADAPTÁVEIS, ADEQUADA, ADMIRAVELMENTE, ADMIRAÇÃO, ADMIRADO, ADORADO, ADORANDO, ADORAÇÃO, VANTAJOSA, VANTAJOSAMENTE, VANTAGENS, AFABILIDADE, AFAVELMENTE, AFINIDADE, AFIRMAÇÃO, AFIRMATIVO, AFLUÊNCIA, PAGAR, ACESSÍVEL, ACESSÍVEL, ÁGIL, ÁGIL, AFABILIDADE, AGRADAVELMENTE, ALINHADOS TUDO VAI BEM, SEDUTOR, SEDUTORA, CURA ALTERNATIVA, ALTRUISTICAMENTE, SURPREENDA, SURPRESA, ESPANTA, SURPREENDENTEMENTE, AMABILIDADE, CORDIALIDADE, AMIGÁVEL, DE FORMA AMIGÁVEL, DIVERTIDO, RECURSO, ATRAENTE, APLAUDIR, APRECIÁVEIS, APRECIADO, APRECIA, APRECIAÇÃO DA BELEZA, COM APREÇO, FOR CASO DISSO, APROVAÇÃO, APROVAR, ARDOR, ARTE DE AGRADECIMENTO, ART DE QUIETUDE, ARTE DE BEM-ESTAR, SEGUROS, POR UMA RAZÃO DE SER, ACARONAR, ACOMODATÍCIA, PALAVRAS INCRÍVEL, BEATIFICAR, BEATITUDE, BENÉFICO, BENEFÍCIO, BENEVOLENTE, AMADA, MELHOR, MELHOR, BLESS, BÊNÇÃO, ABENÇOADO, BLISS, FELIZ, FLOR, BALANCE, EQUILIBRADO, BELEZA, BONITO, LINDAMENTE, PERTENCE, PERTENCENTES, OUSADIA, CORAGEM, BRILHANTE, ALÉM FABULOSO, BRILHANTE, BRILHO, ARDÊNCIA, CEGANDO, BREATHTAKING, BORBULHANDO, REBENTAR, OTIMISMO, VIVACIDADE, FLUTUABILIDADE BRIO, SER EXTRAORDINÁRIO, BE HAPPY, EMBELEZAR, ESTANDO EM REPOUSO, BENFEITOR, BENEFÍCIOS, BENEVOLÊNCIA, ESTADO BENEVOLENTEMENTE, BENEVOLENTEMENTE, O MELHOR DE TODOS OS MUNDOS POSSÍVEIS, ALÉM DE, BELEZA EM TODAS AS COISAS, BEINGNESS, CRÍVEL, IRMÃOS DE SANGUE, CUIDADOS, IMPORTANDO-SE, CALMA, CRIE, CRIATIVO, CRIATIVIDADE, CRIATIVIDADE, CAPAZ, CAPACIDADE, COMPETENTEMENTE, COMEMORAR, CELEBRAÇÃO, CERTOS, CERTEZA, CARITATIVO, CARIDADE, CHARME, ENCANTO, CHARMER, ESCOLHA, CLEAN, LIMPEZA, CONFORTO, CONFORTÁVEL, CONSOLAÇÃO, CUDDLE, CARINHO, SINCERIDADE, CUIDADO, DESAFIO, MUDANÇA, ALEGRE, ALEGRIA, CLARITY, COLABORAÇÃO, O COMPROMETIMENTO, COMUNICAÇÃO, COMUNIDADE, COMPAIXÃO, COMPASSIVO, COMPETENTE, COMPETÊNCIA, COMPETENCY, CONCENTRAÇÃO, CONFIÁVEL, CONFIANÇA, CONSCIÊNCIA, CONSISTÊNCIA, CONSISTENTE, CONTEÚDO, CONTENTAMENTO, CONTINUIDADE, CONTINUANDO, CONTRIBUIÇÃO, CONVICÇÃO, CONVINCENTES, COOPERAÇÃO, CORAGEM, CORTESIA, CORTÊS CURIOSO, CURIOSIDADE, CHAKRA, LEGAL, CLARO DIRIGIDO, CENTRADO, ESTAGNAÇÃO, COMPANHEIRISMO, ATENCIOSO, CONSIDERAÇÃO, COMUNHÃO, CONNECT, CONECTADO, CONEXÃO, CONEXIDADE, CONQUISTAR, BONITO, CARISMA, CARISMÁTICA, RECOLHIDA, VONTADE ALEGRE, ELOGIOS, CONGRUÊNCIA, CORDIAL, CAPITAL, ROLHAGEM, CLARO, CARÍCIA, BOM HUMOR, PALAVRAS DE CORTESIA, CONTENTE, ACONCHEGO, CUTENESS, DIREÇÃO, DELICADO, DECENTE, DESEJÁVEL, DELICIOSO, DELÍCIA, DO, DREAM, SONHADOR, OUSADIA, DETERMINAÇÃO, PRAZER, ENCANTADO, DELICIOSO, FIABILIDADE, DESEJO, DETERMINAÇÃO, DEDICAÇÃO, DIGNIDADE, ASSIDUIDADE, DISCIPLINA, DESCOBERTA, DISCRIÇÃO, DIVERSIDADE, DRIVE, DEVER, DIVINO, DESLUMBRADO, DEVOTADO, AFÁVEL, DESTACAMENTO, DEDICADO, BRILHE, DELICIOSA, EMPATIA, EMPATIA, ENFÁTICO, FÁCIL, FACILMENTE, MAIS FÁCIL, EDUCAR, EDUCAÇÃO, EDUCADO, EFICIENTE, ATIVa, HABILITADO, ENERGÉTICA, ENERGIZE, ENERGIA, ENGAGE, INTERVIR, ENVOLVIDO, ENJOY, PRAZER, BASTANTE, ANSIOSO, ÂNSIA, EFICÁCIA, EFICIÊNCIA, ELEGANCE, INCENTIVE, INCENTIVO, INCENTIVADA, ENDURANCE, IGUALDADE, EXCELÊNCIA, EXCELENTE, EXCITE, EMOÇÃO, ANIMADO, EXPERIÊNCIA, COMPETÊNCIA, EXPLORAÇÃO, EXPRESSIVIDADE, EXPRESSANDO, ILUMINAÇÃO, ETERNO, EXALTAÇÃO, EMULAR, EMPOWER, RESPONSABILIZAR, AUTORIZADO, EXPANSIVO, EMOCIONANTE, ENTUSIASMADO, ENTUSIASMO, REDIGIDO, ENCANTADO, EM TRANSE, EUFÓRICO, EXALTADO, ENCANTADO, EXUBERANTE, EXPECTANTE, EQUÂNIME, ANIMADA, EFICÁCIA, FACILIDADE, EXEMPLARES, EXTRAORDINÁRIO, SÉRIO, ELEVADO, EQUANIMIDADE, FACILIDADE DE MENTE, ANIMADO ANTECIPAÇÃO, EXTRA, EQUIDADE, FÁCIL DE FALAR, DE FÁCIL ABORDAGEM, EUDEMONISMO, EVOLUI, EXALTANDO, EXULTANTE, ASTRONÔMICO, CAMPEÃO ‘, ELÉTRICO, EXCEPCIONAL, EMOCIONANTE, REQUINTADO, SEM ESFORÇO, ECOSOFIA, EFERVESCÊNCIA, ABRACE, AUTORIZANDO PALAVRAS, PALAVRAS ENCORAJADORAS, FANTASTIC, SE SENTIR BEM, SENTIR-SE BEM, FLOW, FLUXO, FABULOSO, FAIR, FÉ, FIEL, FAVORITa, JUSTIÇA, FAMÍLIA, FIDELIDADE, FLEXIBILIDADE, FOCO, FLOREIO, PERDOE, PERDOANDO, PERDÃO, CORAGEM, FREE, LIBERDADE, FRUGALIDADE, FUN, FUTURO, AMIGO, AMIGO, AMIZADE, USO, FASCINADA, CUMPRIR, CUMPRIDAS, FOOD, RESOLUTO, VIÁVEL, FINA, SEM MEDO, FESTIVO, FAMOSO, FANTASIA, ALTIVO, Richard, PIADAS ENGRAÇADAS, OSTENTANDO, GLOW, GENEROSO, GENEROSIDADE, GERAR, GENIAL, GENIUS, GENUÍNO, PRESENTE, DÊ, DAR, BOM, BONDADE, INDO PARA O EXTRA MILE, GRACE, GRATIDÃO, GRATEFULNESS, CRESCER, CRESCIMENTO, GUIA, ORIENTADORES, ORIENTAÇÃO, DEUS, ATERRADA, GLORY, PIEDADE, BONS SENTIMENTOS, VERTIGINOSO, GLAD, BOA SAÚDE, GLAMOUR, RINDO, DEUSA, LINDO, GRANDIOSIDADE, GENERAVITY, CAVALHEIRO, GIGANTESCO, GRANDE, GRANDE, GENGIBRE, BEM-HUMORADA, REPUTAÇÃO, GREATFUL, BOA ESPÍRITO RESIDENTE, BOA PALAVRA, PALAVRAS BOAS, BEM-HUMORADA, REPUTAÇÃO, ESPERANÇA, ESPERANÇA, FELICIDADE, FELIZ, FELIZMENTE, HARMONIOSO, HARMONIZAR, HARMONIA, SAÚDE, SAUDÁVEL, CORAÇÃO, OLÁ, HELP, ÚTIL, AJUDANDO, HOT, HONESTO, HONESTIDADE, HUMANO, HUMOR, GENTILEZA, HERÓI, HEROÍSMO, SANTA, SANTIDADE, HONRA, HOSPITALIDADE, HUMILDE, CÉU, CELESTIAL, HALO, HEARTFELT, RECONFORTANTE, UNIDIRECIONALIDADE, FELIZ HEARTED, DILIGENTE, BONITO, ENORME, HIGH-SPIRITEDNESS, ALTAMENTE DISTINTO, PALAVRAS FELIZ, CORAÇÃO DE ABERTURA, HOSPITALEIRO, PROSPERIDADE HUMANA, ALTAMENTE DISTINTA, IMAGINAÇÃO, INSPIRE, INSPIRAÇÃO, INSPIRADO, INSPIRADO, INCRÍVEL, INOVAR, INOVAÇÃO, INTERESSANTE, JUROS, INTERESSADO, MELHORIA, INDEPENDÊNCIA, INFLUÊNCIA, CRIATIVIDADE, PAZ INTERIOR, INSIGHT, PERSPICAZ, INTEGRIDADE, INTELIGÊNCIA, INTELIGENTE, INTENSIDADE, INTIMIDADE, INTUIÇÃO, CRIATIVIDADE, INVESTIMENTO, INTENÇÃO, REVIGORAR, REVIGORADO, INTRIGADO, ENVOLVER, ENVOLVIDOS, INCLUSÃO, INOCENTE, INEFÁVEL, IDEALISMO, ILUMINAÇÃO, ILUMINADO, INCOMPARÁVEL, INVENCÍVEL, INFINITO, INFINIDADE, ILUSTRE, HABITAÇÃO, PALAVRAS INSPIRADAS, INSPIRAÇÃO PALAVRA, PALAVRAS INSPIRADORAS, ILUSTRE, ALEGRIA, ALEGRIA, PIADA, JOVIAL, APENAS, JUSTIÇA, JUBILANTE, BONDADE, ESPÉCIE, TIPO-CORAÇÃO, GENTILMENTE, BEIJO, CONHECIMENTO, GATINHOS, PALAVRAS AMÁVEIS, GOSTO, PARA RIR, RIR, APRENDER, LEARNING, VIDA, VIVO, VIDA, DE LUXO, LONGEVIDADE, LEALDADE, FIEL, LOVE, ADORÁVEL, AMANDO, LIBERDADE, LIDERANÇA, SORTE, LUCKY, LUZ, BONDADE AMOROSA, BONITO, AMANDO ACEITAÇÃO, SENTIMENTOS AMOROSOS, TRABALHADORES DA LUZ, GUIAR, LUZ DE NEVOEIRO, VIDAS ATRAVÉS, PALAVRAS DO AMOR, AMANTE DA BELEZA, BRILHANTE, BRILHANTE CORES, SIGNIFICADO, SIGNIFICATIVA, MAIS, MAGNÍFICO, MAJESTADE, MUITOS, MARAVILHOSO, MOTIVE, MILAGRE, MÁGICA, FAZENDO UMA DIFERENÇA, MASTERY, MATURIDADE, CONSCIENTE, MINDFULNESS, MODÉSTIA, MOTIVAÇÃO, MOTIVAcIONAL, MISERICÓRDIA, MEDITAÇÃO, ALUCINANTE, MADURO, MOVIDO, MOVIMENTO, MUTUALIDADE, LUTO, MELIORISMO, MAJOR, SUAVE, PALAVRAS SIGNIFICATIVAS, MEMORÁVEL, PALAVRAS MOTIVADO, PALAVRAS DE MOTIVAÇÃO, PALAVRAS INSPIRADORES, MUDANÇAS, NOBRE, ALIMENTANDO, CONSOLIDE, NÃO-RESISTÊNCIA, NÃO RESISTENTE, NOVO, AGRADÁVEL, NIRVANA, PURO, FEITO-NATUREZA, NUTRIR, NUTRIDO, NUTRITIVO, ALIMENTAÇÃO, NAMASTE, NEOTENIA, PALAVRAS BONITAS, OPTIMISTA, OTIMISTA, PENDENTES, OK, ON, EM DIANTE, OPEN, ABERTAMENTE, ABERTURA, DE MENTE ABERTA, OPORTUNIDADE, ORIGINAL, ABERTURA, OTIMISMO, ORDEM, ORGANIZAÇÃO, ORIGINALIDADE, RESULTADO, ORIENTAÇÃO, OBEDIENTE, DE CORAÇÃO ABERTO, OMG, SUPERADO, OM MANI PADME, EXTROVERTIDO, UNIDADE, EXCESSIVAMENTE OTIMISTA, PERFEITO, PERFEIÇÃO, ENERGIA POSITIVA, PENSAMENTOS POSITIVOS, EVENTOS POSITIVOS, CIRCUNSTÂNCIAS POSITIVAS, CRENÇAS POSITIVAS, PAZ, PACIFICAR, PARADISÍACAS, PAIXÃO, APAIXONADO, POR FAVOR, PURE, PERSPECTIVAS, PERSEVERANÇA, PERSISTÊNCIA, CRESCIMENTO PESSOAL, PRAZER, POSITIVO, ATITUDE POSITIVA PALAVRAS, O PODER, PODEROSO, PRATICIDADE, PRECISÃO, PRONTIDÃO, PRESENÇA, PRESERVAÇÃO, PRIVACIDADE, PROATIVIDADE, PROATIVA, PROGRESSO, PROSPERIDADE PRÓSPERO, PONTUALIDADE, PONTUAL, PACIÊNCIA, ORGULHOSO, SATISFEITO, PLAY, BRINCALHÃO, LUDICIDADE, PARTICIPAÇÃO, FINALIDADE, PIAS, FILHOTES DE CACHORRO, EDUCADO, ESPÍRITO POSITIVO, PENSAMENTO POSITIVO, BONITO, MUITO, PERDÃO, PICANTE, POSITUDE, POSSIBILITADO, PRESTEZA, PROTO, IMPAGÁVEL, CORAJOSA, ORGULHO, SENTIMENTOS POSITIVOS, PAZ DE ESPÍRITO, CALMO, EMOÇÕES POSITIVAS, SENTIMENTOS POSITIVOS, VOCABULÁRIO POSITIVO, PALAVRAS DO PODER, PALAVRAS POSITIVAS PODEROSOS, PALAVRAS PODEROSAS, POWER-ON, POWER-UP, PROTEGER, QUALIDADE, CALMO, TRANQUILIDADE, CATITA, DE REPOUSO, RAINHA, ACELERANDO, REPOUSO MENTE, PALAVRAS DE QUALIDADE, RESPEITO, RADIANTE, PRONTO, PRONTIDÃO, REAL, REALIDADE, RAZÃO, RECOMENDAR, REFRESH, REFRESCADO, RELAX, RELAXADO, ALÍVIO, ALIVIAR, ALIVIADO, NOTÁVEL, RACIONALIDADE, O RECONHECIMENTO, RELAÇÕES, CONFIÁVEL, CONFIABILIDADE, RELIGIÃO, DESENVOLTURA, RESPONSABILIDADE, RETIDÃO, ASSUNÇÃO DE RISCOS, ROMANCE, REVELAÇÃO, RESTAURAR, RESTAURADO, REST, DESCANSADO, RENOVAR, RENOVADA, REJUVENESCER, REJUVENESCIDO, ÊXTASE, ARREBATADOR, RESILIENTE, RESILIêNCia, REVERÊNCIA, RIPE, RENASCIDO, PARENTESCO, CEDER, DE RENOME, RESPEITADA, RAINBOW, ROMÂNTICO, CEDER, RENOMADO, ÂMBITO, SMILE, SORRISO, SOULMATE, SOUL, COM ALMA, SAGRADO, SAFE, SEGURANÇA, SEGURO, SEGURO, SEGURANÇA, SUSTENTAR, SUSTENTADO, SAVE, POUPANÇA, SIMPLES, SIMPLIFICAR, ABNEGAÇÃO, AUTO-ESTIMA, SERVIÇO, SIMPLICIDADE, SINCERIDADE, HABILIDADE, HÁBIL, ESPÍRITO, SERENO, SERENIDADE, ESTABILIDADE, RESISTÊNCIA, ESTILO, SISTEMATIZAÇÃO, O AMOR-PRÓPRIO, SE ESFORÇAM, SALVAÇÃO, AUTO-ESTIMA, AUTO-PERDÃO, SERVE, SIMPÁTICO, AUTOCOMPAIXÃO, AUTO-BONDADE, ESTIMULADO, ESTIMULAR, ESTÍMULO, SATISFEITO, AINDA, SURPREENDIDO, SLEEP, EXPRESSÃO SEXUAL, ABRIGO, AUTO-EXPRESSÃO, ESPAÇO, ESPAÇOSOS, ESPONTANEIDADE, ESPONTÂNEA, LUZ DO SOL, SPARK, FAÍSCA, SPARKLES, SWEET, DOÇURA, APOIO, APOIO, SUPORTADO, SUPREME SUCULENTO, QUERIDa, ESTUDO, ESTUDIOSO, SAVOUR, SABOREANDO, SUFICIENTE, ESTUPENDO, GANHOS, SWAGGY, SPLENDID, SMART, ESPETACULAR, ESPECIAL, SERENDIPITY, SINERGIA, SHINE, SHINING, INICIAR, FIRMEZA, SUBLIME, SUNNINESS, SUPERPOTÊNCIA, CORAJOSA, VIRTUOSO, ALMA, PALAVRAS FORTES, TRUE, TRUST, CONFIANTE, TATO, TEACH, DÓCIL, EQUIPE, GRATa, OBRIGADO, OBRIGADO, AGRADECIMENTOS, TERAPIA, TEMPO, TRABALHO EM EQUIPE, OPORTUNIDADE, TOLERÂNCIA, TRADIÇÃO, TRANQUILO, TRANQUILIDADE, VERDADE, VERACIDADE, CONCURSO, EMOCIONADO, TOUCH, TOCADO, AGRADADO, À MATÉRIA, DE SABER, DE SER CONHECIDO, PARA SER VISTO, TRANSFORMADOR, TRANSFORMAÇÃO, TRANSFORMAR, TRIUNFO, THRIVE, PRÓSPERA, TENACIDADE, PARA SER, TRANSPARENTE, COM TERNURA, TEMPO OPTIMISTA, UNIFICAÇÃO, UNIQUE, MELHORIA, ULTIMATE, INCONDICIONAL, UPGRADE, DE FÁCIL UTILIZAÇÃO, UNIDADE, ENTENDE, ENTENDIMENTO, ENTENDIDA, UNIFICAÇÃO DE MENTE, UP, MELHORIA DAS QUALIFICAÇÕES, INACREDITÁVEL, IMPERTURBÁVEL, IRREAL, SURPRESA, OUSADO, PRAZER OUSADO, INSUPORTAVELMENTE BONITO, INACREDITÁVEL, IMPERTURBÁVEL, IRREAL, ESPANTO, VITALIDADE, VALOR, VALORES, VALIOSO, VIRTUOSA, VÁLIDO, VERIFICAR A, MUITO, VIÁVEL, VIRTUDE, VITÓRIA, VITORIOSO, VARIEDADE, VULNERABILIDADE, VULNERÁVEL, VIBRANTE, VOTO, VIM, VIGOR, VENERAÇÃO, VERSATILIDADE, WORTH, DIGNO, DIGNIDADE, RIQUEZA, WARM, O CALOR, BEM-VINDO, DISPOSTOS DISPOSTO, VONTADE, SABEDORIA, SÁBIO, GANHOU, MARAVILHOSO, BEM-ESTAR, SINCERIDADE, MARAVILHA, ÁGUA, POÇO, BEM ESTAR, BEM ESTAR, INTEIRO, TRABALHO, WIN, VENCÍVEL, VENCER, ZELOSO, ZELO, ZEN, Tom, Ler, Nua, Seu, Há, Rua, Oi, Uva, Zé, Nós, Jus, Som, Ló, Gel, Rum, Uns, SUS, Pia, Mãe, Nem, Mil, Rir, Tu, Gás, Jó, Cor, Lua, Via, Um, Asa, Fé, Ser, Dar, Etc, Paz, Bis, Sul, Põe, Ás, Meu, Luz, Diz, Até, Sol, Par, Elo, Gol, Pá, Sul, Sou, Faz, Vó, Cem, Ao, Ter, Fim, Mas, Dia, Lei, Véu, Pai, Sua, Tal, Mar, Com, Vez, Céu, Eu, Sã, Noz, Dez, Sei, Lar, Avô, Ar, Pé, Ver, Rio, Bom, Mim, velocidade, leitura';
let listaMinuscula = frase.split(', ');
let listaFormada = [];
let listaFinal;
let coluna1;
let coluna2;
let coluna3;
let coluna4;

let listaSeparada2e3 = [];
let listaSeparada4e5 = [];
let listaSeparada6e7 = [];
let listaSeparada8e9 = [];
let listaSeparada10eMais = [];

let listaEscolhida = [];

let velMudanca = 10000;

let radioLetras = document.getElementsByName('letras');


const pagina1 = document.querySelector(".op1");
const pagina2 = document.querySelector('.op2');
const pagina3 = document.querySelector('.op3');
const pagina4 = document.querySelector('.op4');

function transformarEmMaiuscula(){
    listaMinuscula.forEach(element => {
        listaFormada.push(element.charAt(0).toUpperCase()+element.slice(1).toLowerCase());
    });
}
transformarEmMaiuscula();


function shuffle(array) {

    var currentIndex = array.length, temporaryValue, randomIndex;
  
    // While there remain elements to shuffle...
    while (0 !== currentIndex) {
  
      // Pick a remaining element...
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex -= 1;
  
      // And swap it with the current element.
      temporaryValue = array[currentIndex];
      array[currentIndex] = array[randomIndex];
      array[randomIndex] = temporaryValue;
    }
  
    return array;
}

function separadorDePalavrasEmListaPorQuantidadeDeLetra(arr){
    arr.forEach(element => {
        if (element.length <= 3) {
            listaSeparada2e3.push(element)
        }
        else if (element.length <=5) {
            listaSeparada4e5.push(element)
        }
        else if (element.length <=7) {
            listaSeparada6e7.push(element)
        }
        else if (element.length <= 9) {
            listaSeparada8e9.push(element)
        }
        else if (element.length >= 10 && element.length < 16) {
            listaSeparada10eMais.push(element)
        }
        
    });
}
separadorDePalavrasEmListaPorQuantidadeDeLetra(listaFormada);


function gerarPalavras() {
    var value;
    radioLetras.forEach(element => {
        if (element.checked){
            value = element.value;
        }
               
    });

    if (value == 'listaSeparada2e3' ) {
        listaFinal = shuffle(listaSeparada2e3)
    }
    else if (value == 'listaSeparada4e5'){
        listaFinal = shuffle(listaSeparada4e5)
    }
    else if (value == 'listaSeparada6e7'){
        listaFinal = shuffle(listaSeparada6e7)
    }
    else if (value == 'listaSeparada8e9'){
        listaFinal = shuffle(listaSeparada8e9)
    }
    else if (value == 'listaSeparada10eMais'){
        listaFinal = shuffle(listaSeparada10eMais)
    }
    // listaFinal = shuffle(arrLetras);
    coluna1 = listaFinal.slice(0,20);
    coluna2 = listaFinal.slice(20,40);
    coluna3 = listaFinal.slice(40,60);
    coluna4 = listaFinal.slice(60,80);
    
    pagina1.innerHTML = null;
    x=0
    coluna1.forEach(element => {
        pagina1.innerHTML += '<p>'
        pagina1.innerHTML += coluna1[x];
        pagina1.innerHTML += '</p>';
        x++
    });

    pagina2.innerHTML = null;
    x=0
    coluna2.forEach(element => {
        pagina2.innerHTML += '<p>'
        pagina2.innerHTML += coluna2[x];
        pagina2.innerHTML += '</p>';
        x++
    });

    pagina3.innerHTML = null;
    x=0
    coluna3.forEach(element => {
        pagina3.innerHTML += '<p>'
        pagina3.innerHTML += coluna3[x];
        pagina3.innerHTML += '</p>';
        x++
    });

    pagina4.innerHTML = null;
    x=0
    coluna4.forEach(element => {
        pagina4.innerHTML += '<p>'
        pagina4.innerHTML += coluna4[x];
        pagina4.innerHTML += '</p>';
        x++
    });
}

gerarPalavras();

// var contador = window.setInterval(function () {
//     gerarPalavras(listaSeparada10eMais);
// }, velMudanca)


separadorDePalavrasEmListaPorQuantidadeDeLetra(listaFormada)
